port: ":8080"

db:
  host: "localhost"
  port: "5432"
  username: "postgres"
  password: "postgres"
  name: "kion_db"
  sslmode: "disable"

data_directory:
  users: "./files/users.csv"
  items: "./files/items.csv"
  interactions: "./files/interactions.csv"
